title: "MG – Networking"
description: "Freelance Technical Scrum Master & Softwareentwickler"
theme: null
markdown: null
plugins: []
exclude:
  - README.md
sass:
  sass_dir: assets/scss
  style: compressed
